version: "3.9"
services:
  api:
    container_name: fanyiqi_api
    build:
      context: ../.
      dockerfile: ../server/containerfile/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../data:/app/data
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
